In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
a = np.zeros(2)

In [6]:
a.size

2

In [7]:
a.shape

(2,)

In [8]:
a.ndim

1

In [9]:
b = np.zeros((4,2,2))

In [10]:
b.shape

(4, 2, 2)

In [11]:
b.size

16

In [12]:
b.ndim

3

In [13]:
type(b)

numpy.ndarray

In [14]:
np.full((5,7),99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [15]:
np.empty((6,2,3))

array([[[1.34758299e-311, 1.34755622e-311, 0.00000000e+000],
        [0.00000000e+000, 1.89146896e-307, 1.16097020e-028]],

       [[1.26138597e-076, 2.54818287e-028, 9.49765748e-043],
        [1.04917183e-153, 5.23081515e-143, 3.79837660e+175]],

       [[1.36993398e-071, 1.08411525e-042, 1.39484685e-075],
        [7.75706123e-144, 3.59751658e+252, 1.46901661e+179]],

       [[8.37404147e+242, 4.31999013e-096, 4.82337723e+228],
        [1.70347422e-051, 1.59722550e+160, 4.96300092e-090]],

       [[2.44996460e-056, 2.74813437e+180, 5.04621343e+180],
        [1.94918963e-153, 6.87626008e+169, 2.32715758e-057]],

       [[2.67736012e+184, 1.51981656e-051, 1.04917650e-153],
        [9.08366791e+223, 5.82381891e-144, 9.73665040e-309]]])

In [20]:
c = np.array([[1,23,3,4]])

In [21]:
c.shape

(1, 4)

In [24]:
c.shape, c.size, c.ndim

((1, 4), 4, 2)

In [23]:
type(c)

numpy.ndarray

In [28]:
np.arange(2,5,2)

array([2, 4])

In [29]:
np.arange(0,5/3,1/3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [32]:
np.arange(0,5/3,0.333333333)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [33]:
np.linspace(0,5/3,6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [36]:
np.random.random((2,3))

array([[0.44293835, 0.67902391, 0.40529169],
       [0.55675844, 0.9206658 , 0.12988178]])

In [39]:
np.random.randint(0,2,(2,3))

array([[1, 1, 0],
       [0, 1, 0]], dtype=int32)

In [40]:
rng = np.random.default_rng(1)

In [41]:
rng.integers(0,2,(2,3))

array([[0, 1, 1],
       [1, 0, 0]])